wandb:
  name: gpt2-sentiment
  offline: False
  project: sentiment_analysis


dataset:
  dir: /home/umutdundar/Desktop/repositories/sentiment-analysis/sentiment_analysis/data/processed
  batch_size: 16
  max_length: 512
  num_workers: 12
  num_classes: 3
  encode_type: gpt2

model:
  name: gpt2
  ckpt: None
  dropout: 0.2


optimizer:
    lr: 3e-4
    betas: [0.9, 0.95]
    weight_decay: 0.01


trainer:
  max_steps: 5000
  precision: 16
  accelerator: auto
  accumulate_grad_batches: 1
  device_type: cpu
