wandb:
  name: gpt2-sentiment-32batch-1e3lr
  offline: False
  project: sentiment_analysis


dataset:
  dir: sentiment_analysis/data/processed
  batch_size: 16
  max_length: 1024
  num_workers: 12
  num_classes: 3
  encode_type: gpt2

model:
  name: gpt2
  ckpt: None
  dropout: 0.2


optimizer:
    lr: 1e-3
    betas: [0.9, 0.95]
    weight_decay: 0.01


trainer:
  max_epochs: 5
  precision: 16
  accelerator: auto
  accumulate_grad_batches: 2
