wandb:
  name: sentiment_analysis
  offline: True
  project: sentiment_analysis
  experiment: sentiment-gpt2

dataset:
  path: data/processed
  batch_size: 8
  max_length: 128
  num_workers: 4

model:
  name: gpt2
  ckpt: None
  