wandb:
  name: nanogpt-sentiment-16batch-1e3
  offline: False
  project: sentiment_analysis

dataset:
  dir: /home/umutdundar/Desktop/repositories/sentiment-analysis/sentiment_analysis/data/processed
  batch_size: 16
  max_length: 512
  num_workers: 12
  num_classes: 3
  encode_type: gpt2

model:
  name: nanogpt
  ckpt: None


optimizer:
    name: Adam
    lr: 1e-3
    betas: [0.9, 0.95]
    weight_decay: 0.01


trainer:
  max_epochs: 10
  precision: 16
  accelerator: auto
  accumulate_grad_batches: 1
  device_type: cuda
