wandb:
  name: sentiment_analysis
  offline: True
  project: sentiment_analysis
  experiment: nanogpt

dataset:
  dir: data/processed
  batch_size: 8
  max_length: 128
  num_workers: 4

model:
  name: nanogpt
  ckpt: None
